= making pancakes
100g plain flour

Pinch of salt
1 Bord Bia Quality Assured egg
300 ml milk
1 tablsp. melted butter or sunflower oil
Sift the flour and salt into a mixing bowl and make a well in the centre.

 

Crack the egg into the well; add the melted butter or oil and half the milk. Gradually draw the flour into the liquid by stirring all the time with a wooden spoon until all the flour has been incorporated and then beat well to make a smooth batter.

 

Stir in the remaining milk. Alternatively, beat all the ingredients together for 1 minute in a blender or food processor.

 

Leave to stand for about 30 minutes, then stir again before using.

 

To make the pancakes, heat a small heavy-based frying until very hot and then turn the heat down to medium.

 

Lightly grease with oil and then ladle in enough batter to coat the base of the pan thinly (about 2 tablsp.), tilting the pan so the mixture spreads evenly.

 

Cook over a moderate heat for 1-2 minutes or until the batter looks dry on the top and begins to brown at the edges. Flip the pancake over with a palette knife or fish slice and cook the second side.
